FROM gitlab.sch.ocrv.com.rzd:4567/public-repos/docker-images/cuda-10.0-ubuntu-18.04-python-3.6:latest

ENV DEVICE "0,"
EXPOSE 80

COPY requirements-base.txt .
COPY requirements-gpu.txt .

RUN git config --global http.sslVerify false && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements-gpu.txt --no-cache-dir && \
    mkdir -p /opt/service

WORKDIR /opt/service

COPY . .
RUN cp settings/local.py.docker settings/local.py

ENTRYPOINT ["python", "manage.py"]
CMD ["run"]
