FROM python:3.6.8

ENV DEVICE cpu
EXPOSE 80

COPY requirements-base.txt .
COPY requirements.txt .

RUN git config --global http.sslVerify false && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt --no-cache-dir && \
    mkdir -p /opt/service

WORKDIR /opt/service

COPY . .
RUN cp settings/local.py.docker settings/local.py

ENTRYPOINT ["python", "manage.py"]
CMD ["run"]
